SmartTimeCVs.Web/Controllers/BiographyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Localization;
using SmartTimeCVs.Web.Core.Dtos;
using SmartTimeCVs.Web.Core.Enums;
using Common;
using Common.Base;

namespace SmartTimeCVs.Web.Controllers
{
    //[Authorize]

    public class BiographyController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IStringLocalizer<SharedResource> _localizer;

        private readonly List<string> _allowedExtensions = new() { ".jpg", ".jpeg", ".png" };
        private readonly List<string> _allowedAttachmentExtensions = new() { ".jpg", ".jpeg", ".png", ".pdf", ".docx" };
        private const int _maxAllowedSize = 5242880; // 5 MB.

        public BiographyController(ApplicationDbContext context, IMapper mapper, IWebHostEnvironment webHostEnvironment, IStringLocalizer<SharedResource> localizer)
        {
            _context = context;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
            _localizer = localizer;
        }

        public async Task<IActionResult> Index()
        {
            string CompanyGuidID;
            string IsCompanyRequest = "";
            if (HttpContext.User.Identity!.IsAuthenticated)
            {
                CompanyGuidID = HttpContext.User.Claims.First(c => c.Type == "CompanyGuidID").Value.ToString();
                IsCompanyRequest = HttpContext.User.Claims.First(c => c.Type == "IsCompanyRequest").Value.ToString();
            }
            else return RedirectToAction("Logout", "Account");
            if (IsCompanyRequest == "True") return RedirectToAction("Logout", "Account");

            using var httpClient = new HttpClient();
            var response = await httpClient.GetFromJsonAsync<SmartTimeCompanyDTO>
                            ($"https://smarttimeapi.zlioustech.com/api/Company/GetCompanyLogoHomePageText/{CompanyGuidID}");

            var currentCulture = Thread.CurrentThread.CurrentUICulture.Name;
            ViewBag.CompanyName = currentCulture.Contains("en") ? response?.Data?.CompanyNameEn : response?.Data?.CompanyNameNative;
            ViewBag.HomePageHtml = currentCulture.Contains("en") ? response?.Data?.HomePageTextEn : response?.Data?.HomePageTextNative;
            ViewBag.CompanyLogo = response?.Data?.CompanyLogo;

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetCustomer(string mobileNumber)
        {
            try
            {
                var customer = await _context.JobApplication
                        .FirstOrDefaultAsync(j => j.CompanyId == GlobalVariablesService.CompanyId && j.MobileNumber.Equals(mobileNumber));

                if (customer is null)
                {
                    return RedirectToAction(nameof(Create), new { mobileNumber = mobileNumber });
                }
                else
                {
                    return RedirectToAction(nameof(Edit), new { id = customer.Id });
                }
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorViewModel { Exception = ex.Message });
            }
        }

        public IActionResult Create(bool isFromJobApplicationView = false, string mobileNumber = "")
        {
            try
            {
                HandleSidebarsViewAndReturnToController(isFromJobApplicationView);

                var initJobApplicationWithMobileNumber = !string.IsNullOrWhiteSpace(mobileNumber) ? new JobApplicationViewModel { MobileNumber = mobileNumber } : null;

                return View("Form", PopulateViewModel(initJobApplicationWithMobileNumber));
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorViewModel { Exception = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(JobApplicationViewModel model)
        {
            using var transaction = await _context.Database.BeginTransactionAsync();

            try
            {
                if (!ModelState.IsValid)
                    return View("Form", PopulateViewModel(model));

                #region Process ImageFile.

                if (model.ImageFile != null)
                {
                    var imageFileName = await ProcessFileAsync(model.ImageFile, "profileImages", "ImageFile");
                    if (!ModelState.IsValid)
                        return View("Form", PopulateViewModel(model));
                    model.ImageUrl = imageFileName;
                }

                #endregion Process ImageFile.

                #region Process CV AttachmentFile.

                if (model.AttachmentFile != null)
                {
                    var attachmentFileName = await ProcessFileAsync(model.AttachmentFile, "cvAttachments", "AttachmentFiles", true);
                    if (!ModelState.IsValid)
                        return View("Form", PopulateViewModel(model));
                    model.AttachmentUrl = attachmentFileName;
                }

                #endregion Process CV AttachmentFile.

                #region Process Work Experience Attachments.

                foreach (var workExperience in model.WorkExperiences)
                {
                    var workExperienceAttachment = workExperience.AttachmentFile;
                    if (workExperienceAttachment != null)
                    {
                        var attachmentFileName = await ProcessFileAsync(workExperienceAttachment, "workExperienceAttachments", "WorkExperienceAttachmentFile", true);
                        if (!ModelState.IsValid)
                            return View("Form", PopulateViewModel(model));
                        workExperience.AttachmentUrl = attachmentFileName;
                    }
                }

                #endregion Process Work Experience Attachments.

                #region Process Attachments.

                foreach (var attachment in model.AttachmentFiles)
                {
                    var attachmentFile = attachment.AttachmentFile;
                    if (attachmentFile != null)
                    {
                        var attachmentFileName = await ProcessFileAsync(attachmentFile, "attachments", "AttachmentFiles", true);
                        if (!ModelState.IsValid)
                            return View("Form", PopulateViewModel(model));
                        attachment.AttachmentUrl = attachmentFileName;
                    }
                }

                #endregion Process Attachments.

                // Map ViewModel to Entity
                var jobApplication = _mapper.Map<JobApplication>(model);
                jobApplication.CompanyId = GlobalVariablesService.CompanyId;
                jobApplication.CreatedOn = DateTime.Now;
                jobApplication.LastUpdatedOn = DateTime.Now;

                // Map and link Universites
                var universites = _mapper.Map<List<University>>(model.Universities);
                jobApplication.Univesity = universites;

                // Map and link Courses
                var courses = _mapper.Map<List<Course>>(model.Courses);
                jobApplication.Course = courses;

                // Map and link WorkExperiences
                var workExperiences = _mapper.Map<List<WorkExperience>>(model.WorkExperiences);
                jobApplication.WorkExperience = workExperiences;

                // Map and link Attachments
                var attachments = _mapper.Map<List<AttachmentFile>>(model.AttachmentFiles);
                jobApplication.AttachmentFiles = attachments;

                // Add and save
                await _context.JobApplication.AddAsync(jobApplication);
                await _context.SaveChangesAsync();

                await transaction.CommitAsync();

                return Json(new { success = true, message = Messages.Saved });
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                ModelState.AddModelError(string.Empty, "An error occurred while saving the data.");
                return View("Error", new ErrorViewModel { Exception = ex.Message });
            }
        }

        public async Task<IActionResult> Edit(int id, bool isFromJobApplicationView = false)
        {
            try
            {
                HandleSidebarsViewAndReturnToController(isFromJobApplicationView);

                var jobApp = await _context.JobApplication.FindAsync(id);

                if (jobApp is null)
                    return NotFound();

                var realtedUniversites = await _context.University.Where(u => u.JobApplicationId == id).ToListAsync();
                var realtedCourses = await _context.Course.Where(c => c.JobApplicationId == id).ToListAsync();
                var realtedWorkExperiences = await _context.WorkExperience.Where(e => e.JobApplicationId == id).ToListAsync();
                var realtedAttachments = await _context.AttachmentFile.Where(e => e.JobApplicationId == id).ToListAsync();

                var viewModel = _mapper.Map<JobApplicationViewModel>(jobApp);

                if (realtedUniversites is not null)
                    viewModel.Universities = _mapper.Map<List<UniversityViewModel>>(realtedUniversites);

                if (realtedCourses is not null)
                    viewModel.Courses = _mapper.Map<List<CourseViewModel>>(realtedCourses);

                if (realtedWorkExperiences is not null)
                    viewModel.WorkExperiences = _mapper.Map<List<WorkExperienceViewModel>>(realtedWorkExperiences);

                if (realtedAttachments is not null)
                    viewModel.AttachmentFiles = _mapper.Map<List<AttachmentFileViewModel>>(realtedAttachments);

SmartTimeCVs.Web/Views/jobApplication/ExcludedIndex.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery
@model IEnumerable<JobApplicationViewModel>
@inject Microsoft.Extensions.Localization.IStringLocalizer<SmartTimeCVs.Web.SharedResource> Localizer

@{
	ViewData["HideSidebars"] = true;
	ViewData["Title"] = @Localizer["JobApplications"];
	ViewData["ControllerName"] = "JobApplication";
	ViewData["Path"] = $"{@Localizer["JobApplications"]} / {@Localizer["Index"]}";
	ViewData["Icon"] = "description";
}

@section Styles {
	<link rel="stylesheet" href="~/theme/assets/css/plugins/datatables.bootstrap4.min.css" />
	<link rel="stylesheet" href="~/lib/animate.css/animate.min.css" />
}

<div class="card shadow-sm">
	<div class="card-header">
		<div class="row justify-content-center">
			<div class="col-6">@*<i class="material-icons breadcrumb theme-main-color align-self-center">@ViewData["Icon"]</i>*@
			</div>
			<div class="col-6">
				@* <a asp-controller="Biography" asp-action="Create" asp-route-isFromJobApplicationView="true" class="btn btn-round btn-info font-bold waves-effect float-end">
					<div class="row">
						<div class="col-md-5 px-2 align-self-center">
							<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
								<path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
							</svg>
						</div>
						<div class="col-md-7 px-1 align-self-center">
							@Localizer["Add"]
						</div>
					</div>
				</a> *@
			</div>
		</div>
	</div>
	<div class="card-body">
		<div class="body table-responsive">
			<table class="table js-datatables" data-document-title="JobApplications">
				<thead>
					<tr class="cyan">
						<th class="js-no-export js-exclude-search d-none">Id</th>
						<th class="js-no-export js-exclude-search">@Localizer["Image"]</th>
						<th>@Localizer["FullName"]</th>
						<th class="js-status-header">@Localizer["Status"]</th>
						<th>@Localizer["ApplicationDate"]</th>
						<th>@Localizer["Mobile"]</th>
						<th>@Localizer["JobTitle"]</th>
						<th class="js-no-export">@Localizer["Attachment"]</th>
						<th class="js-no-export">@Localizer["View"]</th>
						@* <th class="js-no-export">@Localizer["Actions"]</th> *@
					</tr>
				</thead>
				<tbody>
					@foreach (var jobApp in Model)
					{
						<tr>
							<td class="d-none">@jobApp.Id</td>
							<td class="text-center" scope="row"><img class="rounded-circle" src="~/images/profileImages/@(jobApp.ImageUrl is null? "ProfileImagePlaceholder.jpg" : jobApp.ImageUrl)" width="40" height="40" alt="Application image"></td>
							<td scope="row">
								<span class="list-name">@jobApp.FullName</span>
								<br />
								<span class="text-muted">@(jobApp.ApplyingFor ?? string.Empty)</span>
							</td>
							<td class="js-td-status"><span class="badge badge-@(jobApp.IsDeleted? "danger" : "success") js-status">@(jobApp.IsDeleted ? "Deleted" : "Available")</span></td>
							<td>@jobApp.DateOfBirth?.ToDateOfBirth()</td>
							<td>@jobApp.MobileNumber</td>
							@* <td><span class="list-name">@jobApp.Email</span></td> *@
							<td><span class="text-muted">@(jobApp.ApplyingFor ?? string.Empty)</span></td>
							<td class="text-center">
								@if (!string.IsNullOrEmpty(jobApp.AttachmentUrl))
								{
									<a class="btn btn-sm btn-round btn-primary"
									   href="~/images/cvAttachments/@jobApp.AttachmentUrl"
									   target="_blank"
									   download>
										<div class="row">
											<i class="col-md-12 material-icons">file_download</i>
										</div>
									</a>
								}
								else
								{
									<span class="text-muted">No file uploaded</span>
								}
							</td>
							@* <td>
								<ul>
									<li class="dropdown">
										<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
											<i class="material-icons" style=" color: #17a2b8">arrow_drop_down_circle</i>
										</a>
										<ul class="dropdown-menu dropdown-menu-right custom-dropdown-menu js-table-actions">
											@if (!jobApp.IsDeleted)
											{
												<li>
													<a asp-controller="Biography" asp-action="Edit"
													   asp-route-id="@jobApp.Id" asp-route-isFromJobApplicationView="true">
														Edit
													</a>
												</li>
											}
											<li class="js-delete-retrieve" data-id="@jobApp.Id" data-url="/JobApplication/ToggleStatus/@jobApp.Id" data-name="Job Application"><a class="js-toggle" href="javascript:;">@(jobApp.IsDeleted ? "Retrive" : "Delete")</a></li>
										</ul>
									</li>
								</ul>
							</td> *@
                           
                            @* <td>
                                <a asp-controller="JobApplication"
                                   asp-action="ShortList"
                                   asp-route-id="@jobApp.Id"
                                   class="btn btn-sm btn-info">
                                    @Localizer["View"]
                                </a>
                            </td> *@
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>

<input type="hidden" name="__RequestVerificationToken" value="@antiforgery.GetAndStoreTokens(Context).RequestToken" />

@section Plugins {
	<partial name="_DataTablesJS" />
}

SmartTimeCVs.Web/Views/jobApplication/HoldingIndex.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery
@model IEnumerable<JobApplicationViewModel>
@inject Microsoft.Extensions.Localization.IStringLocalizer<SmartTimeCVs.Web.SharedResource> Localizer

@{
	ViewData["HideSidebars"] = true;
	ViewData["Title"] = @Localizer["JobApplications"];
	ViewData["ControllerName"] = "JobApplication";
	ViewData["Path"] = $"{@Localizer["JobApplications"]} / {@Localizer["Index"]}";
	ViewData["Icon"] = "description";
}

@section Styles {
	<link rel="stylesheet" href="~/theme/assets/css/plugins/datatables.bootstrap4.min.css" />
	<link rel="stylesheet" href="~/lib/animate.css/animate.min.css" />
}

<div class="card shadow-sm">
	<div class="card-header">
		<div class="row justify-content-center">
			<div class="col-6">@*<i class="material-icons breadcrumb theme-main-color align-self-center">@ViewData["Icon"]</i>*@
			</div>
			<div class="col-6">
				@* <a asp-controller="Biography" asp-action="Create" asp-route-isFromJobApplicationView="true" class="btn btn-round btn-info font-bold waves-effect float-end">
					<div class="row">
						<div class="col-md-5 px-2 align-self-center">
							<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
								<path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
							</svg>
						</div>
						<div class="col-md-7 px-1 align-self-center">
							@Localizer["Add"]
						</div>
					</div>
				</a> *@
			</div>
		</div>
	</div>
	<div class="card-body">
		<div class="body table-responsive">
			<table class="table js-datatables" data-document-title="JobApplications">
				<thead>
					<tr class="cyan">
						<th class="js-no-export js-exclude-search d-none">Id</th>
						<th class="js-no-export js-exclude-search">@Localizer["Image"]</th>
						<th>@Localizer["FullName"]</th>
						<th class="js-status-header">@Localizer["Status"]</th>
						<th>@Localizer["ApplicationDate"]</th>
						<th>@Localizer["Mobile"]</th>
						<th>@Localizer["JobTitle"]</th>
						<th class="js-no-export">@Localizer["Attachment"]</th>
						<th class="js-no-export">@Localizer["View"]</th>
						@* <th class="js-no-export">@Localizer["Actions"]</th> *@
					</tr>
				</thead>
				<tbody>
					@foreach (var jobApp in Model)
					{
						<tr>
							<td class="d-none">@jobApp.Id</td>
							<td class="text-center" scope="row"><img class="rounded-circle" src="~/images/profileImages/@(jobApp.ImageUrl is null? "ProfileImagePlaceholder.jpg" : jobApp.ImageUrl)" width="40" height="40" alt="Application image"></td>
							<td scope="row">
								<span class="list-name">@jobApp.FullName</span>
								<br />
								<span class="text-muted">@(jobApp.ApplyingFor ?? string.Empty)</span>
							</td>
							<td class="js-td-status"><span class="badge badge-@(jobApp.IsDeleted? "danger" : "success") js-status">@(jobApp.IsDeleted ? "Deleted" : "Available")</span></td>
							<td>@jobApp.DateOfBirth?.ToDateOfBirth()</td>
							<td>@jobApp.MobileNumber</td>
							@* <td><span class="list-name">@jobApp.Email</span></td> *@
							<td><span class="text-muted">@(jobApp.ApplyingFor ?? string.Empty)</span></td>
							<td class="text-center">
								@if (!string.IsNullOrEmpty(jobApp.AttachmentUrl))
								{
									<a class="btn btn-sm btn-round btn-primary"
									   href="~/images/cvAttachments/@jobApp.AttachmentUrl"
									   target="_blank"
									   download>
										<div class="row">
											<i class="col-md-12 material-icons">file_download</i>
										</div>
									</a>
								}
								else
								{
									<span class="text-muted">No file uploaded</span>
								}
							</td>
							@* <td>
								<ul>
									<li class="dropdown">
										<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
											<i class="material-icons" style=" color: #17a2b8">arrow_drop_down_circle</i>
										</a>
										<ul class="dropdown-menu dropdown-menu-right custom-dropdown-menu js-table-actions">
											@if (!jobApp.IsDeleted)
											{
												<li>
													<a asp-controller="Biography" asp-action="Edit"
													   asp-route-id="@jobApp.Id" asp-route-isFromJobApplicationView="true">
														Edit
													</a>
												</li>
											}
											<li class="js-delete-retrieve" data-id="@jobApp.Id" data-url="/JobApplication/ToggleStatus/@jobApp.Id" data-name="Job Application"><a class="js-toggle" href="javascript:;">@(jobApp.IsDeleted ? "Retrive" : "Delete")</a></li>
										</ul>
									</li>
								</ul>
							</td> *@
                            @* <td>
                                <a asp-controller="JobApplication"
                                   asp-action="ShortList"
                                   asp-route-id="@jobApp.Id"
                                   class="btn btn-sm btn-info">
                                    @Localizer["View"]
                                </a>
                            </td> *@
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>

<input type="hidden" name="__RequestVerificationToken" value="@antiforgery.GetAndStoreTokens(Context).RequestToken" />

@section Plugins {
	<partial name="_DataTablesJS" />
}

SmartTimeCVs.Web/Views/jobApplication/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery
@model IEnumerable<JobApplicationViewModel>
@inject Microsoft.Extensions.Localization.IStringLocalizer<SmartTimeCVs.Web.SharedResource> Localizer

@{
	ViewData["HideSidebars"] = true;
	ViewData["Title"] = @Localizer["JobApplications"];
	ViewData["ControllerName"] = "JobApplication";
	ViewData["Path"] = $"{@Localizer["JobApplications"]} / {@Localizer["Index"]}";
	ViewData["Icon"] = "description";
}

@section Styles {
	<link rel="stylesheet" href="~/theme/assets/css/plugins/datatables.bootstrap4.min.css" />
	<link rel="stylesheet" href="~/lib/animate.css/animate.min.css" />
}

<div class="card shadow-sm">
	<div class="card-header">
		<div class="row justify-content-center">
			<div class="col-6">@*<i class="material-icons breadcrumb theme-main-color align-self-center">@ViewData["Icon"]</i>*@
			</div>
			<div class="col-6">
				@* <a asp-controller="Biography" asp-action="Create" asp-route-isFromJobApplicationView="true" class="btn btn-round btn-info font-bold waves-effect float-end">
					<div class="row">
						<div class="col-md-5 px-2 align-self-center">
							<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
								<path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
							</svg>
						</div>
						<div class="col-md-7 px-1 align-self-center">
							@Localizer["Add"]
						</div>
					</div>
				</a> *@
			</div>
		</div>
	</div>
	<div class="card-body">
		<div class="body table-responsive">
			<table class="table js-datatables" data-document-title="JobApplications">
				<thead>
					<tr class="cyan">
						<th class="js-no-export js-exclude-search d-none">Id</th>
						<th class="js-no-export js-exclude-search">@Localizer["Image"]</th>
						<th>@Localizer["FullName"]</th>
						<th class="js-status-header">@Localizer["Status"]</th>
						<th>@Localizer["ApplicationDate"]</th>
						<th>@Localizer["Mobile"]</th>
						<th>@Localizer["JobTitle"]</th>
						<th class="js-no-export">@Localizer["Attachment"]</th>
						<th class="js-no-export">@Localizer["View"]</th>
						@* <th class="js-no-export">@Localizer["Actions"]</th> *@
					</tr>
				</thead>
				<tbody>
					@foreach (var jobApp in Model)
					{
						<tr>
							<td class="d-none">@jobApp.Id</td>
							<td class="text-center" scope="row"><img class="rounded-circle" src="~/images/profileImages/@(jobApp.ImageUrl is null? "ProfileImagePlaceholder.jpg" : jobApp.ImageUrl)" width="40" height="40" alt="Application image"></td>
							<td scope="row">
								<span class="list-name">@jobApp.FullName</span>
								<br />
								<span class="text-muted">@(jobApp.ApplyingFor ?? string.Empty)</span>
							</td>
							<td class="js-td-status"><span class="badge badge-@(jobApp.IsDeleted? "danger" : "success") js-status">@(jobApp.IsDeleted ? "Deleted" : "Available")</span></td>
							<td>@jobApp.DateOfBirth?.ToDateOfBirth()</td>
							<td>@jobApp.MobileNumber</td>
							@* <td><span class="list-name">@jobApp.Email</span></td> *@
							<td><span class="text-muted">@(jobApp.ApplyingFor ?? string.Empty)</span></td>
							<td class="text-center">
								@if (!string.IsNullOrEmpty(jobApp.AttachmentUrl))
								{
									<a class="btn btn-sm btn-round btn-primary"
									   href="~/images/cvAttachments/@jobApp.AttachmentUrl"
									   target="_blank"
									   download>
										<div class="row">
											<i class="col-md-12 material-icons">file_download</i>
										</div>
									</a>
								}
								else
								{
									<span class="text-muted">No file uploaded</span>
								}
							</td>
							@* <td>
								<ul>
									<li class="dropdown">
										<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
											<i class="material-icons" style=" color: #17a2b8">arrow_drop_down_circle</i>
										</a>
										<ul class="dropdown-menu dropdown-menu-right custom-dropdown-menu js-table-actions">
											@if (!jobApp.IsDeleted)
											{
												<li>
													<a asp-controller="Biography" asp-action="Edit"
													   asp-route-id="@jobApp.Id" asp-route-isFromJobApplicationView="true">
														Edit
													</a>
												</li>
											}
											<li class="js-delete-retrieve" data-id="@jobApp.Id" data-url="/JobApplication/ToggleStatus/@jobApp.Id" data-name="Job Application"><a class="js-toggle" href="javascript:;">@(jobApp.IsDeleted ? "Retrive" : "Delete")</a></li>
										</ul>
									</li>
								</ul>
							</td> *@
                            <td>
                                <a asp-controller="JobApplication"
                                   asp-action="View"
                                   asp-route-id="@jobApp.Id"
                                   class="btn btn-sm btn-info">
                                    @Localizer["View"]
                                </a>
                            </td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>

<input type="hidden" name="__RequestVerificationToken" value="@antiforgery.GetAndStoreTokens(Context).RequestToken" />

@section Plugins {
	<partial name="_DataTablesJS" />
}